framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
swiftmailer:
    transport: "smtp"
    host:      "smtp"
    username:  "amiradgham15@gmail.com"
    password:  "amiraaaa55703911"
    spool:     { type: memory }